#include "stdafx.h"


#include "keyCode.h"

namespace mray{

const mchar* EKEY_CODE_String[]=
{
	mT("UNASSIGNED"),
	mT("ESCAPE"),
	mT("1"),
	mT("2"),
	mT("3"),
	mT("4"),
	mT("5"),
	mT("6"),
	mT("7"),
	mT("8"),
	mT("9"),
	mT("0"),
	mT("MINUS"),
	mT("EQUALS"),
	mT("BACK"),
	mT("TAB"),
	mT("Q"),
	mT("W"),
	mT("E"),
	mT("R"),
	mT("T"),
	mT("Y"),
	mT("U"),
	mT("I"),
	mT("O"),
	mT("P"),
	mT("LBRACKET"),
	mT("RBRACKET"),
	mT("RETURN"),
	mT("LCONTROL"),
	mT("A"),
	mT("S"),
	mT("D"),
	mT("F"),
	mT("G"),
	mT("H"),
	mT("J"),
	mT("K"),
	mT("L"),
	mT("SEMICOLON"),
	mT("APOSTROPHE"),
	mT("GRAVE"),
	mT("LSHIFT"),
	mT("BACKSLASH"),
	mT("Z"),
	mT("X"),
	mT("C"),
	mT("V"),
	mT("B"),
	mT("N"),
	mT("M"),
	mT("COMMA"),
	mT("PERIOD"),
	mT("SLASH"),
	mT("RSHIFT"),
	mT("MULTIPLY"),
	mT("LMENU"),
	mT("SPACE"),
	mT("CAPITAL"),
	mT("F1"),
	mT("F2"),
	mT("F3"),
	mT("F4"),
	mT("F5"),
	mT("F6"),
	mT("F7"),
	mT("F8"),
	mT("F9"),
	mT("F10"),
	mT("NUMLOCK"),
	mT("SCROLL"),
	mT("NUMPAD7"),
	mT("NUMPAD8"),
	mT("NUMPAD9"),
	mT("SUBTRACT"),
	mT("NUMPAD4"),
	mT("NUMPAD5"),
	mT("NUMPAD6"),
	mT("ADD"),
	mT("NUMPAD1"),
	mT("NUMPAD2"),
	mT("NUMPAD3"),
	mT("NUMPAD0"),
	mT("DECIMAL"),
	mT("OEM_102"),
	mT("F11"),
	mT("F12"),
	mT("F13"),
	mT("F14"),
	mT("F15"),
	mT("KANA"),
	mT("ABNT_C1"),
	mT("CONVERT"),
	mT("NOCONVERT"),
	mT("YEN"),
	mT("ABNT_C2"),
	mT("NUMPADEQUALS"),
	mT("PREVTRACK"),
	mT("AT"),
	mT("COLON"),
	mT("UNDERLINE"),
	mT("KANJI"),
	mT("STOP"),
	mT("AX"),
	mT("UNLABELED"),
	mT("NEXTTRACK"),
	mT("NUMPADENTER"),
	mT("RCONTROL"),
	mT("MUTE"),
	mT("CALCULATOR"),
	mT("PLAYPAUSE"),
	mT("MEDIASTOP"),
	mT("VOLUMEDOWN"),
	mT("VOLUMEUP"),
	mT("WEBHOME"),
	mT("NUMPADCOMMA"),
	mT("DIVIDE"),
	mT("SYSRQ"),
	mT("RMENU"),
	mT("PAUSE"),
	mT("HOME"),
	mT("UP"),
	mT("PGUP"),
	mT("LEFT"),
	mT("RIGHT"),
	mT("END"),
	mT("DOWN"),
	mT("PGDOWN"),
	mT("INSERT"),
	mT("DELETE"),
	mT("LWIN"),
	mT("RWIN"),
	mT("APPS"),
	mT("POWER"),
	mT("SLEEP"),
	mT("WAKE"),
	mT("WEBSEARCH"),
	mT("WEBFAVORITES"),
	mT("WEBREFRESH "),
	mT("WEBSTOP     "),
	mT("WEBFORWARD"),
	mT("WEBBACK"),
	mT("MYCOMPUTER"),
	mT("MAIL"),
	mT("MEDIASELECT "),
};


const mchar *getCodeString(EKEY_CODE code){
	return EKEY_CODE_String[code];
}

}