#ifndef __wxBasedMyDialog1__
#define __wxBasedMyDialog1__

/**
@file
Subclass of MyDialog1, which is generated by wxFormBuilder.
*/

#include "wxEngineEditor.h"

/** Implementing MyDialog1 */
class wxBasedMyDialog1 : public MyDialog1
{
public:
	/** Constructor */
	wxBasedMyDialog1( wxWindow* parent );
};

#endif // __wxBasedMyDialog1__
