//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XEditor.rc
//
#define IDCANCEL                        2
#define IDC_LOADTEXTURE                 3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_XAXIS_STATUS_BAR             101
#define ID_YAXIS_STATUS_BAR             102
#define IDD_MATERIAL_EDITOR_DLG         103
#define ID_ZAXIS_STATUS_BAR             103
#define ID_STATUSBAR_LOGO               104
#define IDR_MAINFRAME                   128
#define IDR_XEditorTYPE                 129
#define IDD_TEXTURES_DIALOG             129
#define IDB_BITMAP_ICONS                130
#define IDD_SHADERS_DIALOG              130
#define IDD_MATERIALS_DIALOG            131
#define IDD_ANIMATION_BOX               133
#define IDD_NAVIGMESH_TOOLBOX           134
#define IDD_TERRAIN_TOOLBOX             136
#define IDD_ENTITY_PROP_DLG             137
#define IDD_ENVIRONMENT_SETTINGS_DLG    139
#define IDD_SKYBOX_DLG                  140
#define IDD_PLUGIN_DIALOG               147
#define IDD_GAMEACTIONS_DLG             148
#define IDD_LOG_DIALOG                  149
#define IDD_LEVEL_INFO_DLG              150
#define IDD_LOADING_DIALOG              151
#define IDB_LOADING_BMP                 153
#define IDC_SUBMESH_LIST                1000
#define IDC_MTRL_WIREFRAME              1001
#define IDC_MTRL_SMOOTH                 1002
#define IDC_MTRL_ZTEST                  1003
#define IDC_MTRL_ZWRITE                 1004
#define IDC_MTRL_POINTS                 1005
#define IDC_MTRL_CULLFACE               1006
#define IDC_MTRL_ALPHATEST              1007
#define IDC_MTRL_FOG                    1008
#define IDC_MTRL_BLEND                  1009
#define IDC_MTRL_CWCULL                 1010
#define IDC_MTRL_LIGHTING               1011
#define IDC_TEXTURES_LIST               1012
#define IDC_ADD_TEXTURE_BTN             1013
#define IDC_BUTTON1                     1013
#define IDC_GENERATE_NAVMESH_BTN        1013
#define IDC_LOADANIM_BTN                1013
#define IDC_BUTTON2                     1014
#define IDC_IMPORT_NAVMESH_BTN          1014
#define IDC_PLAYANIM_BTN                1014
#define IDC_BUTTON3                     1015
#define IDC_EXPORT_NAVMESH_BTN          1015
#define IDC_STOPANIM_BTN                1015
#define IDC_BUTTON10                    1016
#define IDC_IMPORT_NAVMESH_ATTRS_BTN    1016
#define IDC_BUTTON11                    1017
#define IDC_IMPORT_NAVMESH_BTN2         1017
#define IDC_Load_Attributes_BTN         1017
#define IDC_BUTTON12                    1018
#define IDC_GEN_NORMAL_MAP_BTN          1020
#define IDC_PLUGINS_LIST                1022
#define IDC_INSTALL_PLUGIN_BTN          1023
#define IDC_UNINSTALL_PLUGIN_BTN        1024
#define IDC_REINSTALL_PLUGIN_BTN        1025
#define IDC_GAME_ACTIONS_LIST           1025
#define IDC_DESCRIPTION_TXT             1027
#define IDC_LOG_LIST                    1029
#define IDC_LEVEL_NAME_TXT              1030
#define IDC_LEVEL_DESCRIPTION_TXT       1031
#define IDC_SHININESS                   1032
#define IDC_LEVEL_THUMPNAIL_TXT         1032
#define IDC_VALUES_LIST                 1033
#define IDC_SELECT_THUMBNAIL_BTN        1033
#define IDC_ADD_VALUE                   1034
#define IDC_MAINACTION_NAME_TXT         1034
#define IDC_RMV_VALUE                   1035
#define IDC_SELECT_MAINACTION_BTN       1035
#define IDC_LOADING_PICTURE             1035
#define IDC_SHADERNAME_TXT              1036
#define IDC_LOADING_STATUES_TXT         1036
#define IDC_BUTTON6                     1037
#define IDC_SHADOWSHADER_TXT            1038
#define IDC_DEPTH_SHADER_BTN            1039
#define IDC_VALUETYPE_LIST              1041
#define IDC_SELCET_MATERIAL_BTN         1042
#define IDC_TEXTURENAME_TXT             1044
#define IDC_SHADERS_LIST                1046
#define IDC_LOADSHADER                  1047
#define IDC_DUPLICATE_MTRL              1048
#define IDC_PARAM_V1                    1048
#define IDC_TEXTURE_TYPE                1048
#define IDC_MATERIALS_LIST              1049
#define IDC_PARAM_V2                    1049
#define IDC_PARAM_V3                    1050
#define IDC_PARAM_V4                    1051
#define IDC_TRACKS_LIST                 1051
#define IDC_AMBIENT_BTN                 1053
#define IDC_MATERIAL_NAME               1054
#define IDC_DIFFUSE_BTN                 1056
#define IDC_SPECULAR_BTN                1057
#define IDC_EMISSION_BTN                1058
#define IDC_NAVMESH_MAXSLOPE            1059
#define IDC_NAVMESH_MAXSTEP             1060
#define IDC_NAVMESH_GCELLSZ             1061
#define IDC_COMBO1                      1063
#define IDC_DEST_BLEN_LIST              1064
#define IDC_ALPHA_FUNCTION_LIST         1065
#define IDC_HeightMapTxt                1066
#define IDC_BaseTexTxt                  1067
#define IDC_NormalMapTxt                1068
#define IDC_ATTRIBUTE_LIST              1068
#define IDC_DetailTexTxt                1069
#define IDC_DetailNormalTxt             1070
#define IDC_MOD_ATTR_VALUE_TXT          1072
#define IDC_ACTION_NAME_TXT             1073
#define IDC_ACTION_NAME_BTN             1074
#define IDC_ENTITY_ID_TXT               1075
#define IDC_ENTITYNAME_TXT              1076
#define IDC_TERR_NUM_LODS_TXT           1080
#define IDC_SOURCE_BLEND_LST            1081
#define IDC_SUNDIR_HORIZ_SLD            1082
#define IDC_SUNDIR_VERT_SLD             1083
#define IDC_TERR_LOD_DISTANCE_TXT       1083
#define IDC_SHADOWMAP_W_TXT             1084
#define IDC_TERR_SCALE_X_TXT            1084
#define IDC_SHADOWMAP_H_TXT             1085
#define IDC_TERR_SCALE_Y_TXT            1085
#define IDC_POSTPROCESS_ENABLE_CHK      1086
#define IDC_TERR_SCALE_Z_TXT            1086
#define IDC_FOGDISTANCE_TXT             1087
#define IDC_FOG_ENABLE_CHK              1088
#define IDC_SKYBOX_NAME_TXT             1089
#define IDC_SKYBOX_DLG_BTN              1090
#define IDC_POSTPROCESS_TXT             1091
#define IDC_POSTPROCESS_DLG             1092
#define IDC_CHANGE_SHADOWMAP_BTN        1093
#define IDC_LOADSKYBOX                  1093
#define IDC_SHADOW_FOVY_TXT             1094
#define IDC_SKYBOX_NAME                 1094
#define IDC_SHADOW_ZNEAR_TXT            1095
#define IDC_SKYBOXS_LIST                1095
#define IDC_SHADOW_ASPECT_TXT           1096
#define IDC_SHADOW_ZFAR_TXT5            1097
#define IDC_CHANGE_SHADOW_PROJ_BTN      1098
#define IDR_PANE_OPTIONS                4000
#define IDR_PANE_PROPERTIES             4001
#define IDR_PANE_ENVIRONMENT            4002
#define ID_TOOLS_MATERIALEDITOR         32771
#define ID_TOOLS_TERRAINGENERATOR       32772
#define ID_FILE_LOADSCENE               32773
#define ID_FILE_SAVESCENE               32774
#define ID_FILE_NEWSCENE                32775
#define ID_FILE_LOADMODEL               32776
#define ID_FILE_SAVEMODEL               32777
#define ID_AI_NAVMESHGENERATOR          32778
#define ID_TOOLS_ENVIRONMENT            32779
#define ID_TB_SELECT                    32787
#define ID_TB_TRANSLATE                 32788
#define ID_TB_ROTATE                    32789
#define ID_TB_SCALE                     32790
#define ID_TB_MATERIAL                  32792
#define ID_TB_TERRAIN                   32793
#define ID_TB_NEWSCENE                  32794
#define ID_TB_LOADSCENE                 32795
#define ID_TB_SAVESCENE                 32796
#define ID_SETTINGS_PLUGINS             32797
#define ID_TOOLS_ENTITYPROPERTIES       32798
#define ID_FILE_ADDSEARCHPATH           32799
#define ID_FILE_LEVELINFO               32800
#define ID_SETTINGS_GAMEMODE            32801
#define ID_SETTINGS_LOG                 32802
#define ID_TOOLS_ANIMATION              32803
#define ID_COMPONENTS_PHYSICALCHARACTER 32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
